# Site settings
title: Практикум на ЭВМ, семестр 6
email: andrey.zenzinov@gmail.com
description: "

"
baseurl: "/programming-semester-6/" # the subpath of your site, e.g. /blog/
url: "https://zenderro.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  zenderro

# Build settings
markdown: kramdown
